use dreamcraft_core::{Color, Id, Rect};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SlideLayout {
    TitleSlide,
    TitleAndContent,
    SectionHeader,
    TwoColumns,
    Blank,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum ShapeKind {
    Rectangle,
    RoundedRect { radius: f64 },
    Circle,
    ArrowRight,
    Star,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SlideShape {
    pub id: Id,
    pub kind: ShapeKind,
    pub bounds: Rect,
    pub fill_color: Color,
    pub stroke_color: Option<Color>,
    pub stroke_width: f64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SlideText {
    pub id: Id,
    pub text: String,
    pub bounds: Rect,
    pub font_size: f32,
    pub bold: bool,
    pub color: Color,
    pub is_bullet: bool,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SlideImage {
    pub id: Id,
    pub source_path: String,
    pub bounds: Rect,
    pub alt_text: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Slide {
    pub id: Id,
    pub layout: SlideLayout,
    pub title: String,
    pub subtitle: Option<String>,
    pub background: Color,
    pub shapes: Vec<SlideShape>,
    pub text_boxes: Vec<SlideText>,
    pub images: Vec<SlideImage>,
    pub notes: String,
}

impl Slide {
    pub fn new(layout: SlideLayout, title: impl Into<String>) -> Self {
        Self {
            id: Id::new(),
            layout,
            title: title.into(),
            subtitle: None,
            background: Color::WHITE,
            shapes: Vec::new(),
            text_boxes: Vec::new(),
            images: Vec::new(),
            notes: String::new(),
        }
    }

    pub fn add_bullet(&mut self, text: impl Into<String>, y_offset: f64) {
        self.text_boxes.push(SlideText {
            id: Id::new(),
            text: text.into(),
            bounds: Rect::new(80.0, 160.0 + y_offset, 800.0, 40.0),
            font_size: 20.0,
            bold: false,
            color: Color::BLACK,
            is_bullet: true,
        });
    }

    pub fn add_shape(&mut self, kind: ShapeKind, bounds: Rect, fill_color: Color) {
        self.shapes.push(SlideShape {
            id: Id::new(),
            kind,
            bounds,
            fill_color,
            stroke_color: None,
            stroke_width: 1.0,
        });
    }

    pub fn add_image(&mut self, source_path: impl Into<String>, bounds: Rect) {
        self.images.push(SlideImage {
            id: Id::new(),
            source_path: source_path.into(),
            bounds,
            alt_text: None,
        });
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Presentation {
    pub id: Id,
    pub title: String,
    pub slides: Vec<Slide>,
    pub current_slide: usize,
    pub width: f64,
    pub height: f64,
}

impl Presentation {
    pub fn new(title: impl Into<String>) -> Self {
        let t = title.into();
        let mut first_slide = Slide::new(SlideLayout::TitleSlide, t.clone());
        first_slide.subtitle = Some("Generated by DreamCraft AI".into());
        Self {
            id: Id::new(),
            title: t,
            slides: vec![first_slide],
            current_slide: 0,
            width: 1920.0,
            height: 1080.0,
        }
    }

    pub fn add_slide(&mut self, layout: SlideLayout, title: impl Into<String>) -> usize {
        let slide = Slide::new(layout, title);
        self.slides.push(slide);
        self.slides.len() - 1
    }

    pub fn current_slide_mut(&mut self) -> Option<&mut Slide> {
        self.slides.get_mut(self.current_slide)
    }
}
